stages:
  - test

test:
  stage: test
  image: python:3.9
  before_script:
    - pip install pytest
    - pip install coverage
  script:
    - coverage run -m pytest
    - coverage xml -o coverage.xml
  artifacts:
    paths:
      - coverage.xml

display_coverage:
  stage: test
  image: python:3.9
  before_script:
    - pip install coverage
  script:
    - coverage report
