name: Run Acceptance Tests

on: [push]

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install ChromeDriver
      run: |
        mkdir $HOME/drivers
        curl -L https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -o $HOME/drivers/chromedriver_linux64.zip
        unzip $HOME/drivers/chromedriver_linux64.zip -d $HOME/drivers
        chmod +x $HOME/drivers/chromedriver
        echo "PATH=\$PATH:$HOME/drivers" >> $GITHUB_ENV

    - name: Install Brave
      run: |
        wget https://github.com/brave/brave-browser/releases/download/v1.31.88/brave-browser-1.31.88-linux-x64.zip
        unzip brave-browser-1.31.88-linux-x64.zip
        echo "export PATH=\$PATH:$(pwd)/brave-browser" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install behave
        python -m pip install selenium
        python -m pip install beautifulsoup4

    - name: Run acceptance tests
      run: |
        cd features/steps
        python tests.py








