name: Pruebas de Aceptacion

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Instalar dependencias
      run: |
        pip install behave
        pip install selenium
        # Agrega aquí otras dependencias si las necesitas

    - name: Descargar Brave Browser
      run: curl -SL https://github.com/brave/brave-browser/releases/download/v1.31.88/brave-browser-1.31.88-linux-x64.zip -o brave-browser-1.31.88-linux-x64.zip
    - name: Descomprimir Brave Browser
      run: unzip -o brave-browser-1.31.88-linux-x64.zip -d brave-browser

    - name: Agregar ubicación de Brave Browser al PATH
      run: echo "export PATH=\$PATH:$(pwd)/brave-browser" >> $GITHUB_ENV

    - name: Ejecutar pruebas de aceptación
      run: python tests.py  # Asegúrate de que este comando sea correcto para ejecutar tus pruebas












