name: Selenium Acceptance Tests


on:
  push:
    branches:
      - main  # Cambia "main" por el nombre de tu rama principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código fuente
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Cambia a la versión de Python que necesites, por ejemplo: '3.8'

      - name: Instalar dependencias
        run: |
          python -m pip install behave
          python -m pip install selenium
          python -m pip install beautifulsoup4

      - name: Ejecutar pruebas de aceptación
        run: |
          # Configura la ubicación de los archivos brave.exe y chromedriver.exe según la información que proporcionaste
          export PATH="$PATH:C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
          export PATH="$PATH:C:\\Users\\PC\\Desktop\\Facultad\\5to\\Metodologia\\Agiles\\Ahorcado\\chromedriver.exe"

          # Ejecuta las pruebas de aceptación
          python tests.py








