name: Selenium Acceptance Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install beautifulsoup4
        python -m pip install selenium

    - name: Set up Brave driver
      run: |
        mkdir drivers
        $url = "https://chromedriver.storage.googleapis.com/95.0.4638.17/chromedriver_win32.zip"
        $output = "drivers\chromedriver.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath drivers
        Remove-Item $output

    - name: Verify Brave executable
      run: |
        $brave_path = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
        $app_folder = "C:\Program Files\BraveSoftware\Brave-Browser\Application"
        Get-ChildItem $app_folder
        if (Test-Path $brave_path) {
          Write-Host "Brave executable found."
        } else {
          Write-Host "Brave executable not found."
          exit 1
        }

    - name: Run acceptance tests with Behave and Selenium
      run: |
        $brave_path = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
        $chrome_path = "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\chromedriver.exe"
        behave --define BRAVE_EXECUTABLE_PATH=$brave_path --define CHROME_BINARY_PATH=$chrome_path features





