
name: Run Behave Tests with Playwright

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        pip install behave
        playwright install # Agrega esta línea para instalar los navegadores
        pip install BeautifulSoup4
    - name: Run tests
      run: |
        xvfb-run -a behave iniciar_juego.py



