name: Selenium Acceptance Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install beautifulsoup4
        python -m pip install selenium

    - name: Set up Chrome driver
      run: |
        mkdir -p drivers
        VERSION="95.0.4638.17"
        if [ "$(uname)" = "Darwin" ]; then
          wget -q -O drivers/chromedriver.zip "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_mac64.zip"
        else
          wget -q -O drivers/chromedriver.zip "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip"
        fi
        unzip -q drivers/chromedriver.zip -d drivers
        chmod +x drivers/chromedriver

    - name: Verify Chrome driver version
      run: |
        drivers/chromedriver --version  # Asegurarse de que el controlador esté en la ruta correcta y mostrar su versión

    - name: Set up Brave binary path
      run: |
        echo "export BRAVE_EXECUTABLE_PATH='C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe'" >> $GITHUB_ENV

    - name: Set up Chrome binary path
      run: |
        echo "export CHROME_BINARY_PATH='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'" >> $GITHUB_ENV

    - name: Run acceptance tests with Behave and Selenium
      run: |
        behave features
