name: Test Brave Browser

on: [push]

jobs:
  test_brave:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Download and Install Brave Browser
      run: |
        curl -SL https://github.com/brave/brave-browser/releases/download/v1.31.88/brave-browser-1.31.88-linux-x64.zip -O
        unzip -o brave-browser-1.31.88-linux-x64.zip -d brave-browser
        echo "export PATH=\$PATH:$(pwd)/brave-browser" >> $GITHUB_ENV

    - name: Download and Install ChromeDriver
      run: |
        curl -SL https://chromedriver.storage.googleapis.com/93.0.4577.15/chromedriver_linux64.zip -O
        unzip -o chromedriver_linux64.zip -d chromedriver
        echo "export PATH=\$PATH:$(pwd)/chromedriver" >> $GITHUB_ENV

    - name: Run Behave Tests
      run: |
        behave











