name: Python Unit Tests and Behave

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install beautifulsoup4
        python -m pip install selenium

    - name: Get Brave version
      id: brave_version
      run: |
        BRAVE_VERSION=$(strings /usr/bin/brave-browser | grep "Version=" | head -n 1 | awk -F'=' '{print $2}')
        echo "Brave version: $BRAVE_VERSION"
        echo "::set-output name=version::$BRAVE_VERSION"

    - name: Set up Chrome driver
      run: |
        if test ! -d "drivers"; then
          mkdir drivers
        fi
        VERSION=${{ steps.brave_version.outputs.version }}
        wget -q -O drivers/chromedriver.zip "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip"
        unzip -q drivers/chromedriver.zip -d drivers
        chmod +x drivers/chromedriver

    - name: Run tests with coverage and Behave
      env:
        COVERAGE_FILE: ${{ github.workspace }}/coverage/.coverage
      run: |
        coverage run -m pytest
        coverage xml -o coverage.xml

        mkdir -p coverage
        cp coverage.xml coverage/coverage.xml

        drivers/chromedriver --version  # Para asegurarte de que el controlador esté en la ruta correcta
        behave features








