name: Python Unit Tests and Behave

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install selenium
        python -m pip install beautifulsoup4

    - name: Set up Chrome driver
      run: |
        mkdir -p drivers
        VERSION="95.0.4638.17"
        wget -q -O drivers/chromedriver.zip "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_win32.zip"
        unzip -q drivers/chromedriver.zip -d drivers
        chmod +x drivers/chromedriver

    - name: Run tests with coverage and Behave
      env:
        COVERAGE_FILE: ${{ github.workspace }}/coverage/.coverage
        CHROME_DRIVER_PATH: ${{ github.workspace }}/drivers/chromedriver.exe
        BRAVE_EXECUTABLE_PATH: "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
      run: |
        coverage run -m pytest
        coverage xml -o ${{ github.workspace }}/coverage.xml

        mkdir -p ${{ github.workspace }}/coverage
        cp ${{ github.workspace }}/coverage.xml ${{ github.workspace }}/coverage/coverage.xml

        behave features
















