name: Python Unit Tests and Behave

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install beautifulsoup4
        python -m pip install selenium

    - name: Set up Chrome driver
      run: |
        mkdir -p ${{ github.workspace }}/drivers
        VERSION="95.0.4638.17"
        wget -q -O ${{ github.workspace }}/drivers/chromedriver.zip "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip"
        unzip -q ${{ github.workspace }}/drivers/chromedriver.zip -d ${{ github.workspace }}/drivers
        chmod +x ${{ github.workspace }}/drivers/chromedriver

    - name: Verify Chrome driver version
      run: |
        ${{ github.workspace }}/drivers/chromedriver --version  # Asegurarse de que el controlador esté en la ruta correcta y mostrar su versión

    - name: Run tests with coverage and Behave
      env:
        CHROME_DRIVER_PATH: ${{ github.workspace }}/drivers/chromedriver.exe
        BRAVE_EXECUTABLE_PATH: C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe
        COVERAGE_FILE: ${{ github.workspace }}/coverage/.coverage
      run: |
        python -m behave

        # Resto de los comandos relacionados con las pruebas unitarias y de cobertura...












