name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install behave selenium pytest coverage

      - name: Run Behave tests
        run: behave test.py

      - name: Run unit tests with coverage
        env:
          COVERAGE_FILE: ${{ github.workspace }}/coverage/.coverage
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml

          mkdir -p coverage
          cp coverage.xml coverage/coverage.xml

          coverage report








