name: Python Unit Tests and Behave

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install beautifulsoup4
        python -m pip install selenium

    - name: Set up Chrome driver
      run: |
        mkdir -p "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers"
        VERSION="95.0.4638.17"
        wget -q -O "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers\chromedriver.zip" "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_win32.zip"
        unzip -q "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers\chromedriver.zip" -d "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers"
        chmod +x "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers\chromedriver"

    - name: Verify Chrome driver version
      run: |
        "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers\chromedriver" --version

    - name: Run tests with coverage and Behave
      run: |
        coverage run -m pytest
        coverage xml -o "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage.xml"
        mkdir -p "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage"
        cp "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage.xml" "C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage\coverage.xml"

        behave features















