name: Python Unit Tests and Behave

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install coverage
        python -m pip install behave
        python -m pip install beautifulsoup4
        python -m pip install selenium

    - name: Set up Chrome driver
      run: |
        mkdir drivers
        $env:VERSION="95.0.4638.17"
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_win32.zip" -OutFile drivers\chromedriver.zip
        Expand-Archive -Path drivers\chromedriver.zip -DestinationPath drivers
        Remove-Item drivers\chromedriver.zip

    - name: Verify Chrome driver version
      run: |
        C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\drivers\chromedriver.exe --version  # Asegurarse de que el controlador esté en la ruta correcta y mostrar su versión

    - name: Run tests with coverage and Behave
      env:
        COVERAGE_FILE: C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage\.coverage
      run: |
        coverage run -m pytest
        coverage xml -o C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage.xml

        mkdir C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage
        cp C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage.xml C:\Users\PC\Desktop\Facultad\5to\Metodologia\Agiles\Ahorcado\coverage\coverage.xml

        behave features















