name: Static Code Analysis

on:
  push:
    branches:
      - main  #

jobs:
  lint:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install dependencies
        run: |
            python -m pip install pytest
            python -m pip install coverage
            python -m pip install --upgrade pip
            pip install playwright
            pip install behave
            pip install BeautifulSoup4
      - name: Run Flake8
        run: |
          python -m flake8  

